#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Styling, testing and building your project before commiting'

#check Prettier
yarn check-format ||
(
    echo "Prettier Check Failed. Run yarn format, add changes and try commit again";
    false;
)

#check ESLint
yarn check-lint ||
(
    echo "ESLint Check Failed, Make the required changes listed above, add changes and try to commit again";
    false;
)

#check tsconfig
yarn check-types ||
(
    echo "Failed type check. Make the changes require above, add changes and try to commit again";
    false;
)

echo "Success commit"